### ISSUE TITLE
allow custom weights squared

### ISSUE THREAD

**Issue by francescoalemanno** [francescoalemanno/BayesHistogram.jl#18]
since for already binned data:
`sum(w.^2) != sum(w2)`
we should allow passing a weights2 argument.

@Moelf : wanna have a stab at it?

**Comment by Moelf** [comment]
do you want a breaking change or no

**Comment by francescoalemanno** [comment]
Feel free to reshape the package as much as you like.
I think the uf-api can remain similar to this:
`bayesian_blocks(x[, w=[#, w2 = #], prior = #, min_counts = #, resolution = #])`
