### ISSUE TITLE
supoprt `weight`?

### ISSUE THREAD

**Issue by Moelf** [francescoalemanno/BayesHistogram.jl#2]
Still reading the paper and I'm wondering how does `weights` work with this algorithm, for two reasons:

- The data in HEP has weights (so I assume the paper address it some how)
- I want to use this algorithm for re-binning rather than just binning on raw data

elaborate the point 2 a bit, often the raw data is >> RAM, the best I can do is to first make a really fine-binning histogram, then re-bin it

**Comment by Moelf** [comment]
https://github.com/scikit-hep/hepstats/blob/master/src/hepstats/modeling/bayesian_blocks.py

**Comment by francescoalemanno** [comment]
this https://github.com/francescoalemanno/BayesHistogram.jl/commit/8dedd5cbaec126bb915f17b76b20e70b879c700a should solve it :)

**Comment by francescoalemanno** [comment]
@Moelf let me know if the version with `weights` works out for you

**Comment by Moelf** [comment]
I wonder if we should import tests from scikit hepstats, or did you already run these numbers over there and that's how you obtained the reference?

**Comment by francescoalemanno** [comment]
The `ref` are self-generated, they are there to allow easy refactoring of code.
Importing tests from scikit-hepstats is an excellent idea, but unfortunately I cannot do it myself at this time... 
Would you do it? I would gladly review/accept any PR

**Comment by Moelf** [comment]
yeah I can do it, the idea is simple, run our numbers there and see if we get back the same results.

I surely don't want to import `npy` object...

**Comment by francescoalemanno** [comment]
Ty Jerry!
maybe the only obstacle is the fact that `BayesHistogram.jl` has a `resolution` parameter and a `mincounts` parameter while Scikit-hep does not it seems...

**Comment by francescoalemanno** [comment]
closing this issue, since weights are now supported.
@Moelf : by the way, it would be quite easy to write a small wrapper within FHist to use the function within this package and return a type which is coherent with FHist API.
