### ISSUE TITLE
Disagreement with respect to scikit-hep implementation

### ISSUE THREAD

**Issue by Moelf** [francescoalemanno/BayesHistogram.jl#6]
```julia
julia> using NPZ

julia> npzread("./data_gen.npz")
Dict{String, Vector{Float64}} with 2 entries:
  "weights" => [1.03524, 1.59065, 1.92159, 1.7245, 1.25175, 1.1111, 1.0…
  "data"    => [-1.13384, 0.384319, 1.49655, -0.355382, -0.787534, -0.4…

julia> datas = npzread("./data_gen.npz");

julia> answers = npzread("./answers_bayesian_blocks.npz");

julia> bayesian_blocks(datas["data"]).edges
8-element Vector{Float64}:
 -3.154662950679158
 -2.126058692427544
 -1.5407490071030014
 -0.7146943329219142
  0.6404466881064395
  1.3817680464742417
  2.1781371551736664
  3.265843988558946

julia> answers["be1"]
9-element Vector{Float64}:
 -3.154662950679158
 -2.366746726914241
 -1.8916975822891833
 -1.2379204553303205
 -0.7146943329219142
  0.6404466881064395
  1.3817680464742417
  2.2181565018686125
  3.265843988558946
```

to make the data
```python
import numpy as np
np.random.seed(111)
data1 = np.random.normal(size=1000)
data2 = np.random.normal(2, 1, size=1000)
weights = np.random.uniform(1, 2, size=1000)
np.savez("data_gen.npz", data=data1, weights=weights)
```
here's the output: 
[data_gen.npz.txt](https://github.com/francescoalemanno/BayesHistogram.jl/files/9854555/data_gen.npz.txt)
[answers_bayesian_blocks.npz](https://github.com/scikit-hep/hepstats/raw/master/tests/modeling/data/answers_bayesian_blocks.npz)

**Comment by Moelf** [comment]
remove `min_counts` requirement only fixes partially:
```julia
julia> bayesian_blocks(datas["data"]).edges
10-element Vector{Float64}:
 -3.154662950679158
 -2.366746726914241
 -1.8916975822891833
 -1.2379204553303205
 -0.7146943329219142
  0.6404466881064395
  1.3817680464742417
  2.1551157261763803
  2.645384958044861
  3.265843988558946
```

**Comment by Moelf** [comment]
https://arxiv.org/pdf/1304.2818.pdf has the correct formula

**Comment by Moelf** [comment]
also see https://arxiv.org/src/1207.5578v3/anc/find_blocks.m which has a bug
>num_this = sum( nn_vec( ii_2: ii_2 ) );

should be
>num_this = sum( nn_vec( ii_1: ii_2 ) );

**Comment by francescoalemanno** [comment]
> also see https://arxiv.org/src/1207.5578v3/anc/find_blocks.m which has a bug
> 
> > num_this = sum( nn_vec( ii_2: ii_2 ) );
> 
> should be
> 
> > num_this = sum( nn_vec( ii_1: ii_2 ) );

Fortunately I did not take inspiration from the Matlab implementation



> remove `min_counts` requirement almost fixed it:
> 
> ```julia
> julia> bayesian_blocks(datas["data"]).edges
> 10-element Vector{Float64}:
>  -3.154662950679158
>  -2.366746726914241
>  -1.8916975822891833
>  -1.2379204553303205
>  -0.7146943329219142
>   0.6404466881064395
>   1.3817680464742417
>   2.1551157261763803 #<==== slightly off
>   2.645384958044861 #<===== one of these two extra
>   3.265843988558946
> ```

Are we sure that its the Julia implementation at fault?

**Comment by francescoalemanno** [comment]
@Moelf : finally figured it out, look at this line:
https://github.com/scikit-hep/hepstats/blob/85cdb1e9c0a2699fbe4715ff7c879f068ca7452f/src/hepstats/modeling/bayesian_blocks.py#L154

they use the wrong number of counts within the prior, if the weights are all ones it works fine, but for weighted data that R+1 must be the actual number of counts not the index...

**Comment by Moelf** [comment]
yeah but when comparing without weight I still can't

**Comment by francescoalemanno** [comment]
I think you are right, I just checked again the original paper...
The prior was on the number of splits not on the counts...

**Comment by Moelf** [comment]
yep
```
In [11]: modeling.bayesian_blocks(data["data"])
here
Out[11]:
array([-3.15466295, -2.36674673, -1.89169758, -1.23792046, -0.71469433,
        0.64044669,  1.38176805,  2.2181565 ,  3.26584399])

In [12]: modeling.bayesian_blocks(data["data"])
Out[12]:
array([-3.15466295, -2.36674673, -1.89169758, -1.23792046, -0.71469433,
        0.64044669,  1.38176805,  2.15511573,  2.64538496,  3.26584399])
```

**Comment by Moelf** [comment]
yeah I have a feeling that prior is not gonna make sense for fields other than astro

**Comment by francescoalemanno** [comment]
I think you are right, I closed the PR on their repo since it makes sense for their stuff...

**Comment by Moelf** [comment]
well, technically their repo is for HEP, so this doesn't make sense but LOL

**Comment by francescoalemanno** [comment]
I'm starting to convince myself by looking at the original Matlab code, that the prior makes no sense in the way they implemented it in scikit-hep. I think a more reasonable choice should be based on single bin counts.

**Comment by Moelf** [comment]
haha... idk, I don't have a MATLAB copy right now, but in any case I think the gamma one can be used

**Comment by Moelf** [comment]
@francescoalemanno here's why the N of blocks as prior doesn't make sense:
- The original prior is on how many times the "brightness" changes, which has nothing to do when we adopt it for histograms

**Comment by Moelf** [comment]
I propose we just use gamma prior by default, that's what this paper said anyway: https://arxiv.org/pdf/1708.00810.pdf

>The fitness described above must be modified by a
penalty term for the number of blocks. Without explic-
itly adding this additional parameter, there is an implicit
assumption of a uniform prior on the number of blocks
between 0 and N . This is unreasonable in most cases, as
typically Nb  N , where Nb is the number of blocks. In
Ref. [7] a geometric prior of the form was chosen:
