### ISSUE TITLE
Prior is specific to astrophysics

### ISSUE THREAD

**Issue by Moelf** [francescoalemanno/BayesHistogram.jl#7]
![image](https://user-images.githubusercontent.com/5306213/197619643-87bf1dbc-dbf2-448c-8a30-1a6a7bb8e3a3.png)

**Comment by francescoalemanno** [comment]
this can easily be fixed :)
that -0.478 is much to close to -1/2.
I was looking into this stuff from a theoretical standpoint, infact given a Poisson distribution with mean "N" the Jeffreys prior for such distribution is N^{-1/2}.
Maybe very unsurprisingly their MC study has empirically found that the best prior is a non-informative one.
